# Generated by Django 3.2.3 on 2022-10-01 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('unit_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(default=0)),
                ('observations_text', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Cancelado', 'Cancelado'), ('Despachado', 'Despachado'), ('Entregado', 'Entregado')], default='Activo', max_length=30)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.flower')),
            ],
        ),
    ]
